receta(a,b,c,pollo,e,f).
receta(pizza1,armando3,italiana,salsaaaa,2,comprar).
receta(pizza1,armando,italiana,queso,10,moler).
receta(pizza1,armando,italiana,jamon,15,tomas).
receta(pizza1,armando,italiana,chile,2,picar).
receta(pizza1,armando,italiana,pasta,2,revolver).
receta(pizza1,armando,italiana,salsa,2,comprar).
receta(pizza1,armando4,italiana,sssssalsa,2,comprar).
receta(pizza1,armando2,italiana,pasta,2,revolver).
receta(pizza1,armando2,italiana,salsa,2,comprar).
receta(papasf,yo,italiana,pollo,1,trozar).
receta(coca,armando,italiana,tomate,3,picar).
receta(lasagna,armando,italiana,tomate,3,picar).
